### ISSUE TITLE
Examining wirevector length pre-inference

### ISSUE THREAD

**Issue by timsherwood** [UCSBarchlab/PyRTL#121]
I was looking though the coverage report John got working (thanks John!), and I saw this chunk of code, which must have seemed like a good idea when I wrote in the past, but now seems super sketch.  

Background: one of the features of PyRTL is that you can infer a wirevector length from an assignment if and only if the length of the vector is `None`.    This is really helpful in certain cases (not going to make the argument for that functionality here)

Problem:  What happens should happen with the following code.

```python
foo = WireVector()
print len(foo)
```

Right now this code will print `0` because len is implemented as follows:

```python
    def __len__(self):
        if self.bitwidth is None:
            return 0
        else:
            return self.bitwidth
```

I propose that we instead change len(foo) to throw a PyrtlError exception.

**Comment by Gamrix** [comment]
I agree. I don't think that there really are any places where we would want a undefined bitwidth to be reported as a len of 0.
