### ISSUE TITLE
Move timing.py to rtllib???

### ISSUE THREAD

**Issue by Gamrix** [UCSBarchlab/PyRTL#123]
I feel as though timing.py is not essential or integral enough to be part of the core library. Yes, there will be people who will need it, but people will often need a lot of different things in rtllib. Also, as there are no core dependencies on timing, it could be easily moved to rtllib.

Namespace are a good honking idea, and I feel by filling up the core namespace too much, people will not notice the timing functions. We should give them their own namespace so that people can find a central location for all of the timing functions, and a great place for that is rtllib, where each file is its own namespace (Core has departed namespace internally, but it exposes itself to users as a single namespace).

**Comment by timsherwood** [comment]
I still can't get rtllib to execute for me outside of tox?  /pyrtl is in my pythonpath, do I need to add /pyrtl/rtlib explicitly?

**Comment by Gamrix** [comment]
no, you should only need to do something like ```from pyrtl.rtllib import adders```

**Comment by Gamrix** [comment]
Moved to the analysis folder in commit ea99ee811a59158e723869ebdd6b18456def81ec
