### ISSUE TITLE
Conditional Assignment section in docs?

### ISSUE THREAD

**Issue by jemcmahan13** [UCSBarchlab/PyRTL#129]
I can't find the conditional_update interface in the docs. It looks like the entire section is missing. I'm searching for a function to get the current predicate inside of a `with` block.

**Comment by Gamrix** [comment]
Why exactly do you need to do this???

Also, ask Sherwood what is happening in those bowels. Conditional Assignment is the only part of the codebase that I don't dare touch.

**Comment by jemcmahan13** [comment]
The issue exists to document a lack of something important in the docs.

Getting the current predicate is useful if your building something that sits on top of pyrtl and/or interacts with it. E.g., you want to save an ordered list of predicates to enforce precedence across `with` blocks. or you want to modify the predicates or do additional operations under that condition.
