### ISSUE TITLE
Python 2/3 compatibility on checking name strings

### ISSUE THREAD

**Issue by jemcmahan13** [UCSBarchlab/PyRTL#131]
"Someone" committed a check to make sure that the `WireVector` `name` attribute can only be set to a string, since other code assumes it has string operations (b761f390ed959). The check does not work in both Python 2 and Python 3.

In Python 2, string and unicode strings are different types, both deriving from the base class `basestring`. In Python 3, they were unified into the single type `str`. We need a check that will work for both.

**Comment by timsherwood** [comment]
Is this one closed?
