### ISSUE TITLE
Optimization on non-synthesized blocks?

### ISSUE THREAD

**Issue by jemcmahan13** [UCSBarchlab/PyRTL#132]
The only comment in the `optimize` function says "Return an optimized version of a synthesized hardware block." Does this mean that it should *only* be called on already-synthesized blocks? If so, there's no check in place to ensure the assumption that the block is synthesized. If not, the docstring should be updated.

**Comment by Gamrix** [comment]
I have updated optimize to work on all blocks regardless of whether they have been synthesized. I also have updated the docs to reflect this.
