### ISSUE TITLE
Misusing `<<=` instead of `|=`

### ISSUE THREAD

**Issue by jemcmahan13** [UCSBarchlab/PyRTL#136]
For a wire with conditional assignments, using `<<=` instead of `|=` in one instance will result in a `multiple drivers` error during synthesis. This error could be improved, as in this particular case the problem was the syntactic mis-type of using the wrong assignment operator. Example below.

```python
from pyrtl import *

x = Input(2, "x")
y = Output(1, "y")

with conditional_assignment:
    with x == 0:
        y |= 1
    with x == 1:
        y <<= 0

synthesize()
```

Error: `pyrtl.pyrtlexceptions.PyrtlError: wire y/1O cannot have two drivers`

**Comment by timsherwood** [comment]
I spent some time figuring out how to add a better error message to cover just this case and, while it can be done, it was going to cause a lot of extra code to execute for every wire instantiation and in the end it still would not be caught until late enough that it was not that much better than what I propose: 
changing the error message to read:  Wire "y/1O" has multiple drivers (check for multiple assignments with "<<=" or accidental mixing of "|=" and "<<=").  I will close this issue for now, but if it is still to general I work on targeting those specific errors a bit more.
