### ISSUE TITLE
rename block.as_graph?

### ISSUE THREAD

**Issue by timsherwood** [UCSBarchlab/PyRTL#140]
Block.as_graph seems to be returning a pair of dictionaries rather than a graph (as it used to).  Should we rename this function?  It seems confusing that it would be call as_graph, especially since it is also used for a side effect of checking for duplicate drivers?

**Comment by Gamrix** [comment]
Sure, I am open to suggestions. I named it that because I wanted to replace an old function with the same name.

**Comment by Gamrix** [comment]
We have concluded on the name `net_connections`
