### ISSUE TITLE
Split helperfuncs.py into two files

### ISSUE THREAD

**Issue by Gamrix** [UCSBarchlab/PyRTL#141]
Currently there is a lot of code to make small circuits. For example `and_all_bits`, `mux` and `_basic_mult`. Helperfuncs is ballooning into a massive 600 lines of code file. I am wondering if it would make sense for us to separate this functionality into a `corecircuits.py` file (I'm taking suggestions for names). 

suggested criteria for going into `corecircuits.py`: the code constructs circuitry that is useful for production (not debug).

**Comment by abe-k** [comment]
Another way of splitting up `helperfuncs.py`, which I was considering, is to move the implementations of built-in operators (i.e. the `_basic*` functions) into their own file, and leave the rest as-is. These two splits aren't mutually exclusive, of course.

**Comment by timsherwood** [comment]
Will this change the import path for these functions?

**Comment by Gamrix** [comment]
The plan would be yes for PyRTL internal use. It will not change pyrtl._____ semantics (aka pyrtl.mux will still be pyrtl.mux), but it will change internal function locations. For example helperfuncs.mux will no longer work as it will be in a new file.
