### ISSUE TITLE
`Probe` produces invalid VCD files

### ISSUE THREAD

**Issue by jemcmahan13** [UCSBarchlab/PyRTL#147]
Using the `probe` function and dumping a VCD file results in invalid names that use spaces and colons. Excerpt below from a probe used as: `PC = probe(Register(bitwidth=IHeap.size), "PC")`. Additional lines shown for contrast of well-formed names.

```
$var wire 12 (Probe-1 : PC : tmp146) (Probe-1 : PC : tmp146) $end
$var wire 3 PC_src PC_src $end
$var wire 33 alu_out alu_out $end
```

**Comment by timsherwood** [comment]
Am closing because this has moved to an enhancement I believe (i.e. using NameSanitizer in other places)
