### ISSUE TITLE
Documentation formatting issue

### ISSUE THREAD

**Issue by nvandervoort** [UCSBarchlab/PyRTL#155]
On the ReadTheDocs PyRTL Memory Block page, the description of pyrtl.memory.RomBlock.\_\_init__() is not realizing the :param key for the first three parameters.

linked [here](http://pyrtl.readthedocs.io/en/latest/memory.html)

**Comment by Gamrix** [comment]
fixed in 12315eea0f3af83eb170ba5979e19fc0ab87b289
