### ISSUE TITLE
memory port limitations

### ISSUE THREAD

**Issue by timsherwood** [UCSBarchlab/PyRTL#157]
Building memories with more than 2 read and 1 write port may be problematic from an FPGA synthesis standpoint (2r/2w might be possible too but we need to check).  Suggestion: Add a new parameter to the memory classes that limits the number of ports (throwing an error when more are created) unless explicitly set otherwise.  E.g. max_read_ports=2, max_write_ports=1, where an argument of None indicates there are no limits.  Note: may break some prior code.

**Comment by Gamrix** [comment]
Does anyone have any suggestions as to how to prevent legacy code from breaking (maybe have a `lega cy mode` flag). Or maybe it doesn't matter at all....

**Comment by timsherwood** [comment]
I would say just break it -- the less flags the better (we are still pre 1.0)  After that we can start worrying about backward compatibility.
