### ISSUE TITLE
Refactor AES Encrypt

### ISSUE THREAD

**Issue by Gamrix** [UCSBarchlab/PyRTL#193]
The AES encrypt (not decrypt) state machine should be refactored so that keys are generated the cycle that they are needed instead of being all generated during the first cycle.

**Comment by Gamrix** [comment]
sorry, I thought that it would ask me to confirm before I reverted.

**Comment by nvandervoort** [comment]
So did you want me to put those two statements somewhere outside the state machine?

**Comment by Gamrix** [comment]
Yup, where it was originally

**Comment by nvandervoort** [comment]
But it was inside the state machine function originally...

**Comment by Gamrix** [comment]
Sorry, I didn't mean the mux function literally, I want the `_key_expansion(key_in, round)` and the `_add_round_key` outside of the conditional assignment block.
