### ISSUE TITLE
Signed Integer Multiplication

### ISSUE THREAD

**Issue by Gamrix** [UCSBarchlab/PyRTL#195]
Implement a wrapper around Multiplication that allows for signed values to be inputted

The current multipliers in `rtllib` might  not support signed numbers.
check if they do, and find a way to add signed multiplication if it does not.

**Comment by nvandervoort** [comment]
Do you want every multiplier to have signed support?

**Comment by Gamrix** [comment]
I want something that can take in the Wallace or dada multiplier as an arg and return a version of those multipliers that does signed multiplication.
