### ISSUE TITLE
Generating compute latency numbers and clock cycle break up 

### ISSUE THREAD

**Issue by msharmavikram** [UCSBarchlab/PyRTL#231]
Hey, 

this is an enhancement request. Currently, to the best of my knowledge goes, pyrtl does not support providing the latency numbers of the IP and how the latency distribution (clock cycle distribution) is with different blocks. This data requires to be generated after the synthesis step. (provide number of register path information on the critical path for the data and control signals and at different hierarchy). 

With respect to accuracy of these numbers, well, not needed. One can provide at a high level numbers with 10-15% tolerance. 

regards
vikram

**Comment by timsherwood** [comment]
Hi Vikram,

Take a look in "analysis" subpackage -- there is a class called "TimingAnalysis" which I think will do what you are asking for.   Please reopen if it is not what you are looking for.

John, maybe we need better documentation on that part?  What do you think...
