### ISSUE TITLE
estimate.TimingAnalysis().max_length() has no units in documentation

### ISSUE THREAD

**Issue by DKupshM** [UCSBarchlab/PyRTL#259]
The timing Analysis function in estimate does not have any units. Here is the page for easy reference: https://pyrtl.readthedocs.io/en/latest/analysis.html 
A fix would be to add the correct units in the documentation

**Comment by DKupshM** [comment]
Does anyone know?

**Comment by timsherwood** [comment]
Hey, sorry about not answering before.  If you use "max_freq" it should tell you what you want to know in "MHz".  If you take the inverse of that number it should tell you the critical path delay in microseconds.  If you multiply THAT number by 1000 it should tell you the critical path in nanoseconds.  I will keep this open until I add better comments.
