### ISSUE TITLE
 `from pyrtl.rtllib import adders`

### ISSUE THREAD

**Issue by adaezy** [UCSBarchlab/PyRTL#261]
I am trying to implement the builtin Adder. After doing the import, I get the ripple_add is not defined. Any reason, please?

**Comment by timsherwood** [comment]
Can you post a really simple example that demonstrates this bug for me?

**Comment by timsherwood** [comment]
BTW, I tried the "from pyrtl.rtllib import adders" and it was was working for me.
>>> import pyrtl
>>> from pyrtl.rtllib import adders
>>> adders.ripple_add(...)
If you can post a clearer example that is not working please ropen and I would be happy to look at it.
