### ISSUE TITLE
Extract area delay from yosys

### ISSUE THREAD

**Issue by ti6wb** [UCSBarchlab/PyRTL#274]
Hallo, everybody
For error-free extraction of the area and delay from Yosys (0.9+932) output I had to change line 330 in pyrtl/analysis/estimate.py as follows:
report_lines = [line for line in yosys_output.decode().split('\n') if 'ABC: netlist' in line]

Best regards, 
Wolfgang

**Comment by timsherwood** [comment]
Thanks Wolfgang -- sorry it has been a "little while"  since you posted this, but I just included your change along with a minor refactoring of that code.  Cheers!
