### ISSUE TITLE
Support for identifying Runtime Hardware Error

### ISSUE THREAD

**Issue by jemcmahan13** [UCSBarchlab/PyRTL#39]
Allowing a designer to assign a non-numeric value ("x", "z", etc.) in situations that should be impossible will make it easier to debug design errors.

Actually, a special error class would provide better functionality; if it's encountered in assingment during simulation, an exception can be raised pointing to exactly the source.

Not to future self: Use this + formal method (SAT or some garbage) to prove circuit properties by showing certain conditions are impossibe.

**Comment by timsherwood** [comment]
This is on track to being supported now through `rtl_assert` and `probe` functionality.
