### ISSUE TITLE
Import `collections.abc.Mapping`

### ISSUE THREAD

**Issue by corwin-of-amber** [UCSBarchlab/PyRTL#410]
To support newer Pythons (>= 3.9), this line:
https://github.com/UCSBarchlab/PyRTL/blob/5de365219705cdc1116f3d7efe938f49e888d449/pyrtl/simulation.py#L1031

Should use `collections.abc.Mapping` instead of `collections.Mapping`.

If you need to support both Python 2.x and Python 3.x, you can use one of the methods proposed here:
https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7

**Comment by corwin-of-amber** [comment]
Thanks 🚀 🎸

**Comment by bjourne** [comment]
Think you  can release a  new pypi package with this fix?
