### ISSUE TITLE
Add a helper function to encode 1-hot to binary

### ISSUE THREAD

**Issue by vaaniarora** [UCSBarchlab/PyRTL#455]
https://github.com/intel/rohd-hcl/blob/main/doc/components/onehot.md

Implement a 1-hot to binary that takes a wirevector with only 1 bit set to 1 and returns the bit position of that 1 in binary.

**Comment by Jbalkind** [comment]
I think Michael's `count_zeroes_from_end()` in his PyRTL-Extras should do this: https://github.com/mdko/PyRTL-Extras/blob/master/pyrtl_extras/core.py#L96

**Comment by fdxmw** [comment]
I think you could also implement this with a [prioritized_mux](https://pyrtl.readthedocs.io/en/latest/rtllib.html#pyrtl.rtllib.muxes.prioritized_mux), by passing it a list of `Const`s for its `vals`.
